# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atYj9_lGF7kK0tp-ZjB0e6NVpffMo9LA
"""

import cmath

def solve_quadratic_equation(a, b, c):
    # 計算 delta
    delta = b**2 - 4*a*c

    # 判斷 delta 的值
    if delta >= 0:
        # 計算根
        root1 = (-b + cmath.sqrt(delta)) / (2*a)
        root2 = (-b - cmath.sqrt(delta)) / (2*a)
        return root1, root2
    else:
        # 無實數解
        return None

# 使用者輸入 a、b、c 的值
a = float(input("請輸入 a 的值: "))
b = float(input("請輸入 b 的值: "))
c = float(input("請輸入 c 的值: "))

# 解一元二次方程式
roots = solve_quadratic_equation(a, b, c)

# 輸出解
if roots is not None:
    print("方程式的解為:", roots)
else:
    print("方程式無實數解。")